import mods.nei.NEI;
recipes.removeShaped(<Botania:spawnerClaw>);
<Botania:spawnerClaw>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<Botania:spawnerMover>);
<Botania:spawnerMover>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<ThaumicTinkerer:spawner>);
<ThaumicTinkerer:spawner>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<EnderIO:blockPoweredSpawner>);
<MineFactoryReloaded:machine.1:9>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:portaspawner>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:potatolauncher>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:needlegun>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:rocketlauncher>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:rocket>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:rubberwood.sapling:1>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:rubberwood.sapling:2>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:rubberwood.sapling:3>.addTooltip(format.darkRed("Disabled"));
<MineFactoryReloaded:machine.2:10>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));
<Railcraft:machine.alpha:0>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));#
<Railcraft:machine.alpha:13>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));#
<Railcraft:machine.alpha:4>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));#
recipes.removeShaped(<Railcraft:cart.tnt.wood>);
<Railcraft:cart.tnt.wood>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<Railcraft:cart.anchor>);
<Railcraft:cart.anchor>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));
recipes.removeShaped(<Railcraft:cart.anchor.admin>);
<Railcraft:cart.anchor.admin>.addTooltip(format.darkRed("Disabled; Use Personal Anchor"));
<Railcraft:cart.bore>.addTooltip(format.darkRed("Use at Own Risk"));
recipes.removeShaped(<minecraft:tnt_minecart>);
<minecraft:tnt_minecart>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<HardcoreEnderExpansion:enhanced_tnt>);
<HardcoreEnderExpansion:enhanced_tnt>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<Mekanism:ObsidianTNT>);
<Mekanism:ObsidianTNT>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<TConstruct:explosive.slime>);
<TConstruct:explosive.slime>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<TConstruct:Redstone.Landmine>);
<TConstruct:Redstone.Landmine>.addTooltip(format.darkRed("Disabled"));
<ThermalExpansion:florb>.addTooltip(format.darkRed("Disabled"));
<ThermalExpansion:florb:1>.addTooltip(format.darkRed("Disabled"));
NEI.hide(<ThermalExpansion:florb:1>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.empty>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.standard>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.pierce>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.lava>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.sludge>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.sewage>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.fire>);
NEI.hide(<MineFactoryReloaded:needlegun.ammo.anvil>);
recipes.removeShaped(<EnderZoo:blockConfusingCharge>);
<EnderZoo:blockConfusingCharge>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<EnderZoo:blockEnderCharge>);
<EnderZoo:blockEnderCharge>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<EnderZoo:blockConcussionCharge>);
<EnderZoo:blockConcussionCharge>.addTooltip(format.darkRed("Disabled"));
NEI.hide(<ExtraUtilities:microblocks>);
recipes.removeShaped(<ForbiddenMagic:WrathCage>);
<ForbiddenMagic:WrathCage>.addTooltip(format.darkRed("Disabled"));
NEI.hide(<ForgeMicroblock:microblock>);
NEI.hide(<ForgeMicroblock:microblock:1>);
NEI.hide(<ForgeMicroblock:microblock:2>);
NEI.hide(<ForgeMicroblock:microblock:3>);
NEI.hide(<ForgeMicroblock:microblock:4>);
NEI.hide(<ForgeMicroblock:microblock:258>);
NEI.hide(<Genetics:serumArray>);
NEI.hide(<Genetics:serum>);
NEI.hide(<gendustry:GeneSample>);
recipes.removeShaped(<ImmersiveEngineering:revolver>);
<ImmersiveEngineering:revolver>.addTooltip(format.darkRed("Disabled"));
recipes.removeShaped(<ImmersiveEngineering:bullet>);
NEI.hide(<ImmersiveEngineering:bullet>);
recipes.removeShaped(<OpenBlocks:craneBackpack>);
<OpenBlocks:craneBackpack>.addTooltip(format.darkRed("Disabled"));
